# Generated by Django 2.0.6 on 2018-06-28 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commonName', models.CharField(blank=True, default='', max_length=100)),
                ('scientificName', models.CharField(blank=True, default='', max_length=100)),
                ('family', models.CharField(blank=True, default='', max_length=100)),
                ('imageURL', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'ordering': ('commonName',),
            },
        ),
    ]
